/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Credentials → token pair (or TOTP challenge) + memberships */
        post: operations["AuthController_login_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login/totp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete platform 2FA login */
        post: operations["AuthController_loginTotp_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the refresh token (family-reuse detection) */
        post: operations["AuthController_refresh_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-issue the access token for another owned membership */
        post: operations["AuthController_switch_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session (also ends impersonation) */
        post: operations["AuthController_logout_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke ALL sessions of the account */
        post: operations["AuthController_logoutAll_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session bootstrap: user, memberships, context, toggles */
        get: operations["AuthController_me_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a reset email — 202 always (no enumeration) */
        post: operations["AuthController_forgotPassword_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Consume the single-use token; revokes all sessions */
        post: operations["AuthController_resetPassword_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/totp/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Platform staff: generate the TOTP provisioning secret */
        post: operations["AuthController_totpSetup_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/totp/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Platform staff: arm TOTP, returns one-time recovery codes */
        post: operations["AuthController_totpEnable_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/public/invites/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Invite landing: academy branding + inherited bindings */
        get: operations["PublicInvitesController_landing_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/public/invites/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** The only signup: atomic accept, ends logged in */
        post: operations["PublicInvitesController_accept_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate an invite link bound to the academy (7-day validity) */
        post: operations["InvitesController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invites/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach the invite membership to the authenticated account */
        post: operations["InvitesController_accept_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolved toggle matrix (defaults overlaid with rows) */
        get: operations["AdminPermissionsController_list_v1"];
        /** Upsert permission toggles (registry keys only) */
        put: operations["AdminPermissionsController_update_v1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/platform/academies/{id}/impersonate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Audited 1-hour impersonated admin session for the academy */
        post: operations["PlatformImpersonationController_impersonate_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Student registry with derived Ativo/Pendente badges */
        get: operations["AdminStudentsController_list_v1"];
        put?: never;
        /** Create a student record (minor ⇒ guardian required) */
        post: operations["AdminStudentsController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/students/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Atomic bulk move: whole selection or nothing (capacity-checked) */
        post: operations["AdminStudentsController_move_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/students/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Name-only edit (design backlog: multi-field editing not designed) */
        patch: operations["AdminStudentsController_rename_v1"];
        trace?: never;
    };
    "/v1/admin/students/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Soft archive: inactive + active enrollments ended atomically */
        post: operations["AdminStudentsController_archive_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/guardians": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Guardian registry with dependent counts */
        get: operations["AdminGuardiansController_list_v1"];
        put?: never;
        /** Create a guardian record without a login */
        post: operations["AdminGuardiansController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/guardians/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Name-only edit */
        patch: operations["AdminGuardiansController_rename_v1"];
        trace?: never;
    };
    "/v1/admin/professors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active professor memberships of the academy */
        get: operations["AdminProfessorsController_list_v1"];
        put?: never;
        /** Register a professor: reuse-or-create user by email + membership + set-password email */
        post: operations["AdminProfessorsController_register_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Turmas with schedules, occupancy and derived Lotada */
        get: operations["AdminClassesController_list_v1"];
        put?: never;
        /** Create a recurring turma — weekday chips fan out into schedule rows */
        post: operations["AdminClassesController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/classes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Turma detail: schedule, occupancy, roster */
        get: operations["AdminClassesController_detail_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Name-only edit (schedule/professor/capacity editing deferred) */
        patch: operations["AdminClassesController_rename_v1"];
        trace?: never;
    };
    "/v1/admin/classes/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Soft archive: archived + active enrollments ended atomically */
        post: operations["AdminClassesController_archive_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/classes/{id}/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add to roster (row-locked capacity; reactivates a removed row) */
        post: operations["AdminClassesController_addStudent_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/classes/{id}/students/{studentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove from roster (soft: enrollment flips to removed) */
        delete: operations["AdminClassesController_removeStudent_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/professor/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Minhas turmas: days, times, occupancy */
        get: operations["ProfessorClassesController_list_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/professor/classes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Own turma detail with roster (foreign class → 404) */
        get: operations["ProfessorClassesController_detail_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/professor/classes/{id}/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adicionar aluno — same capacity rule that binds the admin */
        post: operations["ProfessorClassesController_addStudent_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/professor/classes/{id}/students/{studentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove from own roster */
        delete: operations["ProfessorClassesController_removeStudent_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/responsavel/dependents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My children with class and next scheduled slot */
        get: operations["ResponsavelDependentsController_list_v1"];
        put?: never;
        /** Cadastrar filho: auto guardian link + enrollment into the accepted suggestion */
        post: operations["ResponsavelDependentsController_register_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/responsavel/dependents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Child detail (foreign dependent → 404, no existence leak) */
        get: operations["ResponsavelDependentsController_get_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/responsavel/class-suggestion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Age-suggested class for a birth date (null when no match/room) */
        get: operations["ResponsavelDependentsController_suggestion_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginDto: {
            /** @example admin@tatame.dev */
            email: string;
            password: string;
            /**
             * @default cookie
             * @enum {string}
             */
            transport?: "cookie" | "body";
        };
        UserSummaryDto: {
            /** Format: uuid */
            id: string;
            email: string;
            fullName: string;
        };
        MembershipViewDto: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "academy" | "platform";
            /** @enum {string} */
            role: "student" | "professor" | "admin" | "guardian" | "owner" | "support" | "finance";
            /** Format: uuid */
            tenantId: string | null;
            academyName: string | null;
            academySlug: string | null;
            academyStatus: string | null;
            status: string;
        };
        AuthSessionResponseDto: {
            user: components["schemas"]["UserSummaryDto"];
            memberships: components["schemas"]["MembershipViewDto"][];
            /** Format: uuid */
            activeMembershipId: string;
            accessToken: string;
            /** @description Access token TTL in seconds */
            accessExpiresIn: number;
            /** @description Only for `body` transport; web gets the httpOnly cookie */
            refreshToken?: string;
        };
        MfaChallengeResponseDto: {
            /** @enum {boolean} */
            mfaRequired: true;
            /** @description Short-lived token consumed by POST /auth/login/totp */
            challengeToken: string;
        };
        TotpLoginDto: {
            challengeToken: string;
            /** @description TOTP code or single-use recovery code */
            code: string;
            /**
             * @default cookie
             * @enum {string}
             */
            transport?: "cookie" | "body";
        };
        RefreshDto: {
            /** @description Required for body transport; web uses the cookie */
            refreshToken?: string;
            /**
             * @default cookie
             * @enum {string}
             */
            transport?: "cookie" | "body";
        };
        TokenPairResponseDto: {
            accessToken: string;
            /** @description Access token TTL in seconds */
            accessExpiresIn: number;
            /** @description Only for `body` transport; web gets the httpOnly cookie */
            refreshToken?: string;
        };
        SwitchMembershipDto: {
            /** Format: uuid */
            membershipId: string;
        };
        SwitchMembershipResponseDto: {
            accessToken: string;
            /** @description Access token TTL in seconds */
            accessExpiresIn: number;
            /** Format: uuid */
            activeMembershipId: string;
        };
        MeUserDto: {
            /** Format: uuid */
            id: string;
            email: string;
            fullName: string;
            phone: string | null;
            avatarUrl: string | null;
            locale: string;
        };
        MeAcademyDto: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            status: string;
            logoUrl: string | null;
            /** @description White-label 3-color brand input (deep/vibrant/accent) when configured */
            theme: {
                [key: string]: unknown;
            } | null;
        };
        MeImpersonationDto: {
            isImpersonated: boolean;
            /** Format: uuid */
            impersonatorUserId?: string | null;
        };
        MeResponseDto: {
            user: components["schemas"]["MeUserDto"];
            memberships: components["schemas"]["MembershipViewDto"][];
            /**
             * Format: uuid
             * @description Null during impersonation
             */
            activeMembershipId: string | null;
            /** @enum {string} */
            activeRole: "student" | "professor" | "admin" | "guardian" | "owner" | "support" | "finance";
            academy: components["schemas"]["MeAcademyDto"] | null;
            permissions: {
                [key: string]: boolean;
            };
            impersonation: components["schemas"]["MeImpersonationDto"];
        };
        ForgotPasswordDto: {
            email: string;
        };
        ForgotPasswordResponseDto: {
            /** @enum {boolean} */
            accepted: true;
        };
        ResetPasswordDto: {
            token: string;
            newPassword: string;
        };
        TotpSetupResponseDto: {
            /** @description Base32 provisioning secret */
            secret: string;
            /** @description otpauth:// URI for authenticator apps */
            otpauthUri: string;
        };
        TotpEnableDto: {
            /** @description Code from the authenticator app */
            code: string;
        };
        TotpEnableResponseDto: {
            /** @description Single-use recovery codes — shown exactly once */
            recoveryCodes: string[];
        };
        InviteAcademyDto: {
            name: string;
            slug: string;
            logoUrl: string | null;
            /** @description White-label 3-color brand input (deep/vibrant/accent) when configured */
            theme: {
                [key: string]: unknown;
            } | null;
        };
        InviteLandingResponseDto: {
            /** @enum {string} */
            kind: "student" | "guardian";
            /** Format: date-time */
            expiresAt: string;
            /** Format: uuid */
            classId: string | null;
            /** Format: uuid */
            academyPlanId: string | null;
            academy: components["schemas"]["InviteAcademyDto"];
        };
        DependentDto: {
            fullName: string;
            /** @example 2015-04-20 */
            birthDate: string;
        };
        AcceptInviteDto: {
            email: string;
            password: string;
            fullName: string;
            phone?: string;
            /** @example 1996-02-11 */
            birthDate?: string;
            /** @description Guardian (responsável) invites only: minor dependents enrolled with the guardian. Consumed by the enrollment slice. */
            dependents?: components["schemas"]["DependentDto"][];
        };
        InviteAcceptResponseDto: {
            user: components["schemas"]["UserSummaryDto"];
            memberships: components["schemas"]["MembershipViewDto"][];
            /** Format: uuid */
            activeMembershipId: string;
            accessToken: string;
            /** @description Access token TTL in seconds */
            accessExpiresIn: number;
            /** @description Always in the body — the client stores it per its platform contract */
            refreshToken: string;
            /** @description True when the invite-bound class was full (or archived) at accept time: signup succeeded, the enrollment was skipped (spec 003, story 39) */
            enrollmentSkipped?: boolean;
        };
        CreateInviteDto: {
            /** @enum {string} */
            kind: "student" | "guardian";
            /**
             * Format: uuid
             * @description Turma binding (class slice)
             */
            classId?: string;
            /**
             * Format: uuid
             * @description Academy plan binding (billing slice)
             */
            academyPlanId?: string;
            /** @description Absent = unlimited until expiry */
            maxUses?: number;
        };
        CreateInviteResponseDto: {
            /** @description Raw invite token — returned exactly once */
            token: string;
            /** Format: date-time */
            expiresAt: string;
            /** @enum {string} */
            kind: "student" | "guardian";
        };
        AttachInviteResponseDto: {
            /** Format: uuid */
            membershipId: string;
            /** Format: uuid */
            tenantId: string;
            /** @enum {string} */
            role: "student" | "professor" | "admin" | "guardian";
        };
        ResolvedPermissionDto: {
            /** @enum {string} */
            role: "student" | "professor" | "admin" | "guardian";
            /** @description Registry key, e.g. `invites.create` */
            key: string;
            /** @description PT-BR handoff label (admin screen copy) */
            label: string;
            defaultAllowed: boolean;
            allowed: boolean;
        };
        PermissionMatrixResponseDto: {
            permissions: components["schemas"]["ResolvedPermissionDto"][];
        };
        PermissionEntryDto: {
            /** @enum {string} */
            role: "student" | "professor" | "admin" | "guardian";
            /** @example invites.create */
            key: string;
            allowed: boolean;
        };
        UpdatePermissionsDto: {
            entries: components["schemas"]["PermissionEntryDto"][];
        };
        ImpersonationAcademyDto: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            status: string;
        };
        ImpersonationGrantResponseDto: {
            accessToken: string;
            /** @description Access token TTL in seconds */
            accessExpiresIn: number;
            /** @description Always in the body: the platform refresh cookie stays untouched */
            refreshToken: string;
            /**
             * Format: date-time
             * @description 1-hour absolute cap
             */
            expiresAt: string;
            academy: components["schemas"]["ImpersonationAcademyDto"];
        };
        ClassRefDto: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        StudentListItemDto: {
            /** Format: uuid */
            id: string;
            fullName: string;
            /** @example 2010-04-20 */
            birthDate: string;
            /** @enum {string} */
            status: "active" | "inactive";
            /**
             * @description Derived: pendente = record not yet claimed by a login
             * @enum {string}
             */
            badge: "ativo" | "pendente";
            /** Format: uuid */
            guardianId: string | null;
            /** Format: uuid */
            userId: string | null;
            /** @description Active enrollments */
            classes: components["schemas"]["ClassRefDto"][];
        };
        StudentListResponseDto: {
            students: components["schemas"]["StudentListItemDto"][];
        };
        CreateStudentDto: {
            fullName: string;
            /** @example 2010-04-20 */
            birthDate: string;
            /**
             * Format: uuid
             * @description Required when the student is a minor (minor ⇒ guardian rule)
             */
            guardianId?: string;
        };
        StudentResponseDto: {
            student: components["schemas"]["StudentListItemDto"];
        };
        MoveStudentsDto: {
            studentIds: string[];
            /** Format: uuid */
            destinationClassId: string;
        };
        MoveStudentsResponseDto: {
            /** Format: uuid */
            destinationClassId: string;
            /** @description Every selected student — the move is atomic */
            movedStudentIds: string[];
        };
        UpdateNameDto: {
            fullName: string;
        };
        GuardianListItemDto: {
            /** Format: uuid */
            id: string;
            fullName: string;
            phone: string | null;
            email: string | null;
            /** @enum {string} */
            badge: "ativo" | "pendente";
            /** Format: uuid */
            userId: string | null;
            dependentCount: number;
        };
        GuardianListResponseDto: {
            guardians: components["schemas"]["GuardianListItemDto"][];
        };
        CreateGuardianDto: {
            fullName: string;
            phone?: string;
            email?: string;
        };
        GuardianResponseDto: {
            guardian: components["schemas"]["GuardianListItemDto"];
        };
        ProfessorListItemDto: {
            /** Format: uuid */
            membershipId: string;
            /** Format: uuid */
            userId: string;
            fullName: string;
            email: string;
            /** @description Membership status */
            status: string;
        };
        ProfessorListResponseDto: {
            professors: components["schemas"]["ProfessorListItemDto"][];
        };
        RegisterProfessorDto: {
            fullName: string;
            /** @description Reused cross-tenant when an account already exists */
            email: string;
        };
        RegisterProfessorResponseDto: {
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            membershipId: string;
            /** @description False when an existing account was reused by email */
            userCreated: boolean;
            /** @description True when the set-your-password email was dispatched (no credential yet) */
            passwordEmailSent: boolean;
        };
        ClassProfessorDto: {
            /** Format: uuid */
            userId: string;
            fullName: string;
        };
        ScheduleSlotViewDto: {
            /** @description 0 = Sunday … 6 = Saturday */
            weekday: number;
            /** @example 19:00 */
            startTime: string;
            durationMinutes: number;
        };
        ClassListItemDto: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            status: "active" | "archived";
            capacity: number;
            /** @description Active enrollment count — server-derived */
            occupancy: number;
            /** @description Derived: occupancy ≥ capacity */
            lotada: boolean;
            ageMin: number | null;
            ageMax: number | null;
            professor: components["schemas"]["ClassProfessorDto"];
            schedules: components["schemas"]["ScheduleSlotViewDto"][];
        };
        ClassListResponseDto: {
            classes: components["schemas"]["ClassListItemDto"][];
        };
        ScheduleSlotDto: {
            /** @description 0 = Sunday … 6 = Saturday */
            weekday: number;
            /**
             * @description HH:MM (24h)
             * @example 19:00
             */
            startTime: string;
            durationMinutes: number;
        };
        CreateClassDto: {
            name: string;
            /**
             * Format: uuid
             * @description Must hold an active professor membership
             */
            professorUserId: string;
            /** @description Student limit — "Lotada" when reached */
            capacity: number;
            /** @description Optional age range (Kids chip) */
            ageMin?: number;
            ageMax?: number;
            schedules: components["schemas"]["ScheduleSlotDto"][];
        };
        RosterStudentDto: {
            /** Format: uuid */
            studentId: string;
            fullName: string;
            /** @example 2010-04-20 */
            birthDate: string;
            /** @enum {string} */
            badge: "ativo" | "pendente";
        };
        ClassDetailDto: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            status: "active" | "archived";
            capacity: number;
            /** @description Active enrollment count — server-derived */
            occupancy: number;
            /** @description Derived: occupancy ≥ capacity */
            lotada: boolean;
            ageMin: number | null;
            ageMax: number | null;
            professor: components["schemas"]["ClassProfessorDto"];
            schedules: components["schemas"]["ScheduleSlotViewDto"][];
            /** @description Active roster */
            roster: components["schemas"]["RosterStudentDto"][];
        };
        ClassDetailResponseDto: {
            class: components["schemas"]["ClassDetailDto"];
        };
        UpdateClassNameDto: {
            name: string;
        };
        AddRosterStudentDto: {
            /** Format: uuid */
            studentId: string;
        };
        EnrollmentResultDto: {
            /** Format: uuid */
            classId: string;
            /** Format: uuid */
            studentId: string;
            /** @enum {string} */
            status: "active" | "removed";
        };
        EnrollmentResultResponseDto: {
            enrollment: components["schemas"]["EnrollmentResultDto"];
        };
        DependentClassDto: {
            /** Format: uuid */
            id: string;
            name: string;
            schedules: components["schemas"]["ScheduleSlotViewDto"][];
            /** @description Next scheduled slot, server-derived */
            nextSlot: components["schemas"]["ScheduleSlotViewDto"] | null;
        };
        DependentDetailDto: {
            /** Format: uuid */
            id: string;
            fullName: string;
            /** @example 2017-06-10 */
            birthDate: string;
            /** @enum {string} */
            status: "active" | "inactive";
            /** @description Active class if enrolled */
            class: components["schemas"]["DependentClassDto"] | null;
        };
        DependentListResponseDto: {
            dependents: components["schemas"]["DependentDetailDto"][];
        };
        DependentResponseDto: {
            dependent: components["schemas"]["DependentDetailDto"];
        };
        RegisterDependentDto: {
            fullName: string;
            /** @example 2017-06-10 */
            birthDate: string;
            /**
             * Format: uuid
             * @description Accepted age-suggested class. Registration succeeds even when it is full — the enrollment is skipped (story 34).
             */
            classId?: string;
        };
        RegisterDependentResponseDto: {
            dependent: components["schemas"]["DependentDetailDto"];
            /** @description False when no class was accepted or the accepted class was full (story 34) */
            enrolled: boolean;
        };
        ClassSuggestionDto: {
            /** Format: uuid */
            id: string;
            name: string;
            ageMin: number | null;
            ageMax: number | null;
            capacity: number;
            occupancy: number;
            schedules: components["schemas"]["ScheduleSlotViewDto"][];
        };
        ClassSuggestionResponseDto: {
            /** @description Null when no active age-matching class with a free slot exists */
            suggestion?: components["schemas"]["ClassSuggestionDto"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_login_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponseDto"];
                };
            };
            /** @description Platform 2FA challenge */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaChallengeResponseDto"];
                };
            };
        };
    };
    AuthController_loginTotp_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TotpLoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponseDto"];
                };
            };
        };
    };
    AuthController_refresh_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairResponseDto"];
                };
            };
        };
    };
    AuthController_switch_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchMembershipDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SwitchMembershipResponseDto"];
                };
            };
        };
    };
    AuthController_logout_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logoutAll_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponseDto"];
                };
            };
        };
    };
    AuthController_forgotPassword_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordDto"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForgotPasswordResponseDto"];
                };
            };
        };
    };
    AuthController_resetPassword_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_totpSetup_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TotpSetupResponseDto"];
                };
            };
        };
    };
    AuthController_totpEnable_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TotpEnableDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TotpEnableResponseDto"];
                };
            };
        };
    };
    PublicInvitesController_landing_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteLandingResponseDto"];
                };
            };
        };
    };
    PublicInvitesController_accept_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInviteDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteAcceptResponseDto"];
                };
            };
        };
    };
    InvitesController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInviteDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateInviteResponseDto"];
                };
            };
        };
    };
    InvitesController_accept_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachInviteResponseDto"];
                };
            };
        };
    };
    AdminPermissionsController_list_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionMatrixResponseDto"];
                };
            };
        };
    };
    AdminPermissionsController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePermissionsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionMatrixResponseDto"];
                };
            };
        };
    };
    PlatformImpersonationController_impersonate_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImpersonationGrantResponseDto"];
                };
            };
        };
    };
    AdminStudentsController_list_v1: {
        parameters: {
            query?: {
                /** @description Default `active` — archived records are hidden from active listings */
                status?: "active" | "inactive" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentListResponseDto"];
                };
            };
        };
    };
    AdminStudentsController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStudentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentResponseDto"];
                };
            };
        };
    };
    AdminStudentsController_move_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveStudentsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoveStudentsResponseDto"];
                };
            };
        };
    };
    AdminStudentsController_rename_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNameDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentResponseDto"];
                };
            };
        };
    };
    AdminStudentsController_archive_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminGuardiansController_list_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuardianListResponseDto"];
                };
            };
        };
    };
    AdminGuardiansController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGuardianDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuardianResponseDto"];
                };
            };
        };
    };
    AdminGuardiansController_rename_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNameDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuardianResponseDto"];
                };
            };
        };
    };
    AdminProfessorsController_list_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfessorListResponseDto"];
                };
            };
        };
    };
    AdminProfessorsController_register_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterProfessorDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterProfessorResponseDto"];
                };
            };
        };
    };
    AdminClassesController_list_v1: {
        parameters: {
            query?: {
                /** @description Default `active` — archived records are hidden from active listings */
                status?: "active" | "inactive" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassListResponseDto"];
                };
            };
        };
    };
    AdminClassesController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClassDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassDetailResponseDto"];
                };
            };
        };
    };
    AdminClassesController_detail_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassDetailResponseDto"];
                };
            };
        };
    };
    AdminClassesController_rename_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateClassNameDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassDetailResponseDto"];
                };
            };
        };
    };
    AdminClassesController_archive_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminClassesController_addStudent_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddRosterStudentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentResultResponseDto"];
                };
            };
        };
    };
    AdminClassesController_removeStudent_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                studentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentResultResponseDto"];
                };
            };
        };
    };
    ProfessorClassesController_list_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassListResponseDto"];
                };
            };
        };
    };
    ProfessorClassesController_detail_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassDetailResponseDto"];
                };
            };
        };
    };
    ProfessorClassesController_addStudent_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddRosterStudentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentResultResponseDto"];
                };
            };
        };
    };
    ProfessorClassesController_removeStudent_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                studentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentResultResponseDto"];
                };
            };
        };
    };
    ResponsavelDependentsController_list_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DependentListResponseDto"];
                };
            };
        };
    };
    ResponsavelDependentsController_register_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDependentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterDependentResponseDto"];
                };
            };
        };
    };
    ResponsavelDependentsController_get_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DependentResponseDto"];
                };
            };
        };
    };
    ResponsavelDependentsController_suggestion_v1: {
        parameters: {
            query: {
                birthDate: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassSuggestionResponseDto"];
                };
            };
        };
    };
}
