/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Credentials → token pair (or TOTP challenge) + memberships */
        post: operations["AuthController_login_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login/totp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete platform 2FA login */
        post: operations["AuthController_loginTotp_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the refresh token (family-reuse detection) */
        post: operations["AuthController_refresh_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-issue the access token for another owned membership */
        post: operations["AuthController_switch_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session (also ends impersonation) */
        post: operations["AuthController_logout_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke ALL sessions of the account */
        post: operations["AuthController_logoutAll_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session bootstrap: user, memberships, context, toggles */
        get: operations["AuthController_me_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a reset email — 202 always (no enumeration) */
        post: operations["AuthController_forgotPassword_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Consume the single-use token; revokes all sessions */
        post: operations["AuthController_resetPassword_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/totp/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Platform staff: generate the TOTP provisioning secret */
        post: operations["AuthController_totpSetup_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/totp/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Platform staff: arm TOTP, returns one-time recovery codes */
        post: operations["AuthController_totpEnable_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/public/invites/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Invite landing: academy branding + inherited bindings */
        get: operations["PublicInvitesController_landing_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/public/invites/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** The only signup: atomic accept, ends logged in */
        post: operations["PublicInvitesController_accept_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate an invite link bound to the academy (7-day validity) */
        post: operations["InvitesController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invites/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach the invite membership to the authenticated account */
        post: operations["InvitesController_accept_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolved toggle matrix (defaults overlaid with rows) */
        get: operations["AdminPermissionsController_list_v1"];
        /** Upsert permission toggles (registry keys only) */
        put: operations["AdminPermissionsController_update_v1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/platform/academies/{id}/impersonate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Audited 1-hour impersonated admin session for the academy */
        post: operations["PlatformImpersonationController_impersonate_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginDto: {
            /** @example admin@tatame.dev */
            email: string;
            password: string;
            /**
             * @default cookie
             * @enum {string}
             */
            transport?: "cookie" | "body";
        };
        UserSummaryDto: {
            /** Format: uuid */
            id: string;
            email: string;
            fullName: string;
        };
        MembershipViewDto: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "academy" | "platform";
            /** @enum {string} */
            role: "student" | "professor" | "admin" | "guardian" | "owner" | "support" | "finance";
            /** Format: uuid */
            tenantId: string | null;
            academyName: string | null;
            academySlug: string | null;
            academyStatus: string | null;
            status: string;
        };
        AuthSessionResponseDto: {
            user: components["schemas"]["UserSummaryDto"];
            memberships: components["schemas"]["MembershipViewDto"][];
            /** Format: uuid */
            activeMembershipId: string;
            accessToken: string;
            /** @description Access token TTL in seconds */
            accessExpiresIn: number;
            /** @description Only for `body` transport; web gets the httpOnly cookie */
            refreshToken?: string;
        };
        MfaChallengeResponseDto: {
            /** @enum {boolean} */
            mfaRequired: true;
            /** @description Short-lived token consumed by POST /auth/login/totp */
            challengeToken: string;
        };
        TotpLoginDto: {
            challengeToken: string;
            /** @description TOTP code or single-use recovery code */
            code: string;
            /**
             * @default cookie
             * @enum {string}
             */
            transport?: "cookie" | "body";
        };
        RefreshDto: {
            /** @description Required for body transport; web uses the cookie */
            refreshToken?: string;
            /**
             * @default cookie
             * @enum {string}
             */
            transport?: "cookie" | "body";
        };
        TokenPairResponseDto: {
            accessToken: string;
            /** @description Access token TTL in seconds */
            accessExpiresIn: number;
            /** @description Only for `body` transport; web gets the httpOnly cookie */
            refreshToken?: string;
        };
        SwitchMembershipDto: {
            /** Format: uuid */
            membershipId: string;
        };
        SwitchMembershipResponseDto: {
            accessToken: string;
            /** @description Access token TTL in seconds */
            accessExpiresIn: number;
            /** Format: uuid */
            activeMembershipId: string;
        };
        MeUserDto: {
            /** Format: uuid */
            id: string;
            email: string;
            fullName: string;
            phone: string | null;
            avatarUrl: string | null;
            locale: string;
        };
        MeAcademyDto: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            status: string;
            logoUrl: string | null;
            /** @description White-label 3-color brand input (deep/vibrant/accent) when configured */
            theme: {
                [key: string]: unknown;
            } | null;
        };
        MeImpersonationDto: {
            isImpersonated: boolean;
            /** Format: uuid */
            impersonatorUserId?: string | null;
        };
        MeResponseDto: {
            user: components["schemas"]["MeUserDto"];
            memberships: components["schemas"]["MembershipViewDto"][];
            /**
             * Format: uuid
             * @description Null during impersonation
             */
            activeMembershipId: string | null;
            /** @enum {string} */
            activeRole: "student" | "professor" | "admin" | "guardian" | "owner" | "support" | "finance";
            academy: components["schemas"]["MeAcademyDto"] | null;
            permissions: {
                [key: string]: boolean;
            };
            impersonation: components["schemas"]["MeImpersonationDto"];
        };
        ForgotPasswordDto: {
            email: string;
        };
        ForgotPasswordResponseDto: {
            /** @enum {boolean} */
            accepted: true;
        };
        ResetPasswordDto: {
            token: string;
            newPassword: string;
        };
        TotpSetupResponseDto: {
            /** @description Base32 provisioning secret */
            secret: string;
            /** @description otpauth:// URI for authenticator apps */
            otpauthUri: string;
        };
        TotpEnableDto: {
            /** @description Code from the authenticator app */
            code: string;
        };
        TotpEnableResponseDto: {
            /** @description Single-use recovery codes — shown exactly once */
            recoveryCodes: string[];
        };
        InviteAcademyDto: {
            name: string;
            slug: string;
            logoUrl: string | null;
            /** @description White-label 3-color brand input (deep/vibrant/accent) when configured */
            theme: {
                [key: string]: unknown;
            } | null;
        };
        InviteLandingResponseDto: {
            /** @enum {string} */
            kind: "student" | "guardian";
            /** Format: date-time */
            expiresAt: string;
            /** Format: uuid */
            classId: string | null;
            /** Format: uuid */
            academyPlanId: string | null;
            academy: components["schemas"]["InviteAcademyDto"];
        };
        DependentDto: {
            fullName: string;
            /** @example 2015-04-20 */
            birthDate: string;
        };
        AcceptInviteDto: {
            email: string;
            password: string;
            fullName: string;
            phone?: string;
            /** @example 1996-02-11 */
            birthDate?: string;
            /** @description Guardian (responsável) invites only: minor dependents enrolled with the guardian. Consumed by the enrollment slice. */
            dependents?: components["schemas"]["DependentDto"][];
        };
        InviteAcceptResponseDto: {
            user: components["schemas"]["UserSummaryDto"];
            memberships: components["schemas"]["MembershipViewDto"][];
            /** Format: uuid */
            activeMembershipId: string;
            accessToken: string;
            /** @description Access token TTL in seconds */
            accessExpiresIn: number;
            /** @description Always in the body — the client stores it per its platform contract */
            refreshToken: string;
        };
        CreateInviteDto: {
            /** @enum {string} */
            kind: "student" | "guardian";
            /**
             * Format: uuid
             * @description Turma binding (class slice)
             */
            classId?: string;
            /**
             * Format: uuid
             * @description Academy plan binding (billing slice)
             */
            academyPlanId?: string;
            /** @description Absent = unlimited until expiry */
            maxUses?: number;
        };
        CreateInviteResponseDto: {
            /** @description Raw invite token — returned exactly once */
            token: string;
            /** Format: date-time */
            expiresAt: string;
            /** @enum {string} */
            kind: "student" | "guardian";
        };
        AttachInviteResponseDto: {
            /** Format: uuid */
            membershipId: string;
            /** Format: uuid */
            tenantId: string;
            /** @enum {string} */
            role: "student" | "professor" | "admin" | "guardian";
        };
        ResolvedPermissionDto: {
            /** @enum {string} */
            role: "student" | "professor" | "admin" | "guardian";
            /** @description Registry key, e.g. `invites.create` */
            key: string;
            /** @description PT-BR handoff label (admin screen copy) */
            label: string;
            defaultAllowed: boolean;
            allowed: boolean;
        };
        PermissionMatrixResponseDto: {
            permissions: components["schemas"]["ResolvedPermissionDto"][];
        };
        PermissionEntryDto: {
            /** @enum {string} */
            role: "student" | "professor" | "admin" | "guardian";
            /** @example invites.create */
            key: string;
            allowed: boolean;
        };
        UpdatePermissionsDto: {
            entries: components["schemas"]["PermissionEntryDto"][];
        };
        ImpersonationAcademyDto: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            status: string;
        };
        ImpersonationGrantResponseDto: {
            accessToken: string;
            /** @description Access token TTL in seconds */
            accessExpiresIn: number;
            /** @description Always in the body: the platform refresh cookie stays untouched */
            refreshToken: string;
            /**
             * Format: date-time
             * @description 1-hour absolute cap
             */
            expiresAt: string;
            academy: components["schemas"]["ImpersonationAcademyDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_login_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponseDto"];
                };
            };
            /** @description Platform 2FA challenge */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaChallengeResponseDto"];
                };
            };
        };
    };
    AuthController_loginTotp_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TotpLoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponseDto"];
                };
            };
        };
    };
    AuthController_refresh_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairResponseDto"];
                };
            };
        };
    };
    AuthController_switch_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchMembershipDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SwitchMembershipResponseDto"];
                };
            };
        };
    };
    AuthController_logout_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logoutAll_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponseDto"];
                };
            };
        };
    };
    AuthController_forgotPassword_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordDto"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForgotPasswordResponseDto"];
                };
            };
        };
    };
    AuthController_resetPassword_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_totpSetup_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TotpSetupResponseDto"];
                };
            };
        };
    };
    AuthController_totpEnable_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TotpEnableDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TotpEnableResponseDto"];
                };
            };
        };
    };
    PublicInvitesController_landing_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteLandingResponseDto"];
                };
            };
        };
    };
    PublicInvitesController_accept_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInviteDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteAcceptResponseDto"];
                };
            };
        };
    };
    InvitesController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInviteDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateInviteResponseDto"];
                };
            };
        };
    };
    InvitesController_accept_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachInviteResponseDto"];
                };
            };
        };
    };
    AdminPermissionsController_list_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionMatrixResponseDto"];
                };
            };
        };
    };
    AdminPermissionsController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePermissionsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionMatrixResponseDto"];
                };
            };
        };
    };
    PlatformImpersonationController_impersonate_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImpersonationGrantResponseDto"];
                };
            };
        };
    };
}
