package br.com.tatame.core.designsystem.palette

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Golden-fixture parity test (DS.8 / spec 002 Testing Decisions).
 *
 * `palette-fixtures.json` is generated by the canonical TS executor
 * (`packages/design-system/src/theme/derive-palette.ts`) and committed here
 * verbatim. Every hex the Kotlin port produces must be byte-equal (uppercase
 * #RRGGBB) to the fixture — any drift between the TS and Kotlin OKLab math
 * fails this test instead of shipping mismatched tenant colors.
 */
class DerivePaletteTest {

    private val fixtures = Json
        .parseToJsonElement(loadFixtures())
        .jsonObject
        .getValue("fixtures")
        .jsonObject

    private fun loadFixtures(): String =
        checkNotNull(javaClass.classLoader?.getResourceAsStream("palette-fixtures.json")) {
            "palette-fixtures.json missing from test resources"
        }.bufferedReader().use { it.readText() }

    @Test
    fun `covers all four ready-made presets`() {
        assertEquals(setOf("roxo", "navy", "verde", "preto"), fixtures.keys)
    }

    @Test
    fun `derivePalette reproduces every golden fixture byte-equal`() {
        var assertions = 0
        for ((presetName, presetElement) in fixtures) {
            val preset = presetElement.jsonObject
            val brandObj = preset.getValue("brand").jsonObject
            val brand = BrandInput(
                deep = brandObj.getValue("deep").jsonPrimitive.content,
                vibrant = brandObj.getValue("vibrant").jsonPrimitive.content,
                accent = brandObj.getValue("accent").jsonPrimitive.content,
            )

            for ((modeKey, mode) in mapOf("light" to Mode.LIGHT, "dark" to Mode.DARK)) {
                val expected = preset.getValue(modeKey).jsonObject
                    .mapValues { (_, v) -> v.jsonPrimitive.content }
                val actual = derivePalette(brand, mode)

                assertEquals(
                    "$presetName/$modeKey: token set drifted",
                    expected.keys,
                    actual.keys,
                )
                for ((token, expectedHex) in expected) {
                    assertEquals(
                        "$presetName/$modeKey/$token",
                        expectedHex,
                        actual.getValue(token),
                    )
                    assertions++
                }
            }
        }
        // 4 presets x 2 modes x 21 tokens — guard against silently empty fixtures.
        assertEquals(168, assertions)
    }

    @Test
    fun `output is normalized uppercase RRGGBB hex`() {
        val palette = derivePalette(
            BrandInput(deep = "#4f2389", vibrant = "#8b3deb", accent = "#ec5bae"),
            Mode.LIGHT,
        )
        for ((token, hex) in palette) {
            assertTrue("$token: \"$hex\" is not #RRGGBB uppercase", hex.matches(Regex("^#[0-9A-F]{6}$")))
        }
        // Lowercase brand input passes through normalized, not re-mixed.
        assertEquals("#4F2389", palette.getValue("purple-700"))
    }
}
