// Golden-fixture parity tests for the Swift DerivePalette port (spec 002).
//
// Resources/palette-fixtures.json is a committed copy of
// packages/design-system/tokens/palette-fixtures.json — generated by the
// canonical TypeScript executor (4 ready-made presets x 2 modes). Every hex
// here must reproduce byte-equal; any drift between the Swift port and the
// TS executor fails this suite instead of shipping mismatched tenant colors.

import Foundation
import Testing
@testable import DesignSystem

private struct FixtureFile: Decodable {
    let fixtures: [String: Fixture]
}

private struct Fixture: Decodable {
    let brand: Brand
    let light: [String: String]
    let dark: [String: String]

    struct Brand: Decodable {
        let deep: String
        let vibrant: String
        let accent: String
    }
}

private func loadFixtures() throws -> [String: Fixture] {
    let url = try #require(
        Bundle.module.url(forResource: "palette-fixtures", withExtension: "json")
    )
    return try JSONDecoder().decode(FixtureFile.self, from: Data(contentsOf: url)).fixtures
}

@Suite("DerivePalette golden fixtures")
struct DerivePaletteGoldenTests {
    @Test("reproduces every fixture hex byte-equal", arguments: PaletteMode.allCases)
    func goldenParity(mode: PaletteMode) throws {
        let fixtures = try loadFixtures()
        #expect(fixtures.count == 4)

        for (preset, fixture) in fixtures {
            let brand = BrandInput(
                deep: fixture.brand.deep,
                vibrant: fixture.brand.vibrant,
                accent: fixture.brand.accent
            )
            let expected = mode == .light ? fixture.light : fixture.dark
            let derived = try derivePalette(brand, mode: mode)

            // Same token set, no extras and no omissions.
            #expect(
                Set(derived.keys) == Set(expected.keys),
                "token set mismatch for preset \(preset) (\(mode))"
            )
            for (token, expectedHex) in expected {
                #expect(
                    derived[token] == expectedHex,
                    "\(preset)/\(mode)/\(token): got \(derived[token] ?? "nil"), want \(expectedHex)"
                )
            }
        }
    }

    @Test("brand inputs pass through bit-exact, uppercased")
    func plainCopyNormalization() throws {
        let derived = try derivePalette(
            BrandInput(deep: "#4f2389", vibrant: "8b3deb", accent: "#EC5BAE"),
            mode: .light
        )
        #expect(derived["purple-700"] == "#4F2389")
        #expect(derived["purple-500"] == "#8B3DEB")
        #expect(derived["pink-500"] == "#EC5BAE")
    }

    @Test("invalid hex throws")
    func invalidHex() {
        #expect(throws: DerivePaletteError.invalidHex("#XYZXYZ")) {
            _ = try derivePalette(
                BrandInput(deep: "#XYZXYZ", vibrant: "#8B3DEB", accent: "#EC5BAE"),
                mode: .light
            )
        }
    }

    @Test("theme scaffold exposes derived colors")
    func themeScaffold() {
        let theme = TatameTheme() // default brand, light
        #expect(theme.palette["purple-700"] == "#4F2389")
        #expect(theme.color("purple-700") != nil)
        #expect(theme.color("not-a-token") == nil)
    }
}
