/**
 * GENERATED FILE — do not edit by hand.
 *
 * TypeScript mirror of `tokens/palette-recipe.json`, regenerated by the
 * `design-system:tokens` target (tokens/build.mjs). The JSON file is the
 * canonical recipe; this module exists so TS source never imports JSON
 * (nodenext + import attributes friction). A vitest test asserts this
 * mirror is byte-identical in content to the JSON.
 */

export type RecipeBase = 'deep' | 'vibrant' | 'accent';

export interface RecipeRule {
  readonly base: RecipeBase;
  readonly pct: number;
  /** Literal hex, an input slot name, symbolic "W", or null (plain copy). */
  readonly anchor: string | null;
}

export interface RecipeEntry extends Partial<RecipeRule> {
  readonly token: string;
  readonly modes?: { readonly light: RecipeRule; readonly dark: RecipeRule };
  readonly extrapolated?: boolean;
}

export interface PaletteRecipe {
  readonly anchors: { readonly W: { readonly light: string; readonly dark: string } };
  readonly entries: readonly RecipeEntry[];
}

export const PALETTE_RECIPE: PaletteRecipe = {
  "anchors": {
    "W": {
      "light": "#FFFFFF",
      "dark": "#241E3A"
    }
  },
  "entries": [
    {
      "token": "purple-700",
      "base": "deep",
      "pct": 100,
      "anchor": null
    },
    {
      "token": "purple-500",
      "base": "vibrant",
      "pct": 100,
      "anchor": null
    },
    {
      "token": "pink-500",
      "base": "accent",
      "pct": 100,
      "anchor": null
    },
    {
      "token": "purple-600",
      "base": "deep",
      "pct": 50,
      "anchor": "vibrant"
    },
    {
      "token": "purple-800",
      "base": "deep",
      "pct": 72,
      "anchor": "#12061F"
    },
    {
      "token": "purple-900",
      "base": "deep",
      "pct": 52,
      "anchor": "#0E0518"
    },
    {
      "token": "purple-950",
      "base": "deep",
      "pct": 34,
      "anchor": "#0A0512"
    },
    {
      "token": "purple-400",
      "base": "vibrant",
      "pct": 72,
      "anchor": "W"
    },
    {
      "token": "purple-300",
      "base": "vibrant",
      "pct": 46,
      "anchor": "W"
    },
    {
      "token": "purple-200",
      "base": "vibrant",
      "pct": 27,
      "anchor": "W"
    },
    {
      "token": "purple-100",
      "base": "vibrant",
      "pct": 14,
      "anchor": "W"
    },
    {
      "token": "purple-50",
      "base": "vibrant",
      "pct": 6,
      "anchor": "W"
    },
    {
      "token": "purple-ink",
      "modes": {
        "light": {
          "base": "deep",
          "pct": 100,
          "anchor": null
        },
        "dark": {
          "base": "vibrant",
          "pct": 65,
          "anchor": "#FFFFFF"
        }
      }
    },
    {
      "token": "pink-ink",
      "modes": {
        "light": {
          "base": "accent",
          "pct": 64,
          "anchor": "#3B0A24"
        },
        "dark": {
          "base": "accent",
          "pct": 60,
          "anchor": "#FFFFFF"
        }
      }
    },
    {
      "token": "pink-700",
      "base": "accent",
      "pct": 64,
      "anchor": "#3B0A24"
    },
    {
      "token": "pink-600",
      "base": "accent",
      "pct": 80,
      "anchor": "#3B0A24"
    },
    {
      "token": "pink-400",
      "base": "accent",
      "pct": 72,
      "anchor": "W"
    },
    {
      "token": "pink-300",
      "base": "accent",
      "pct": 46,
      "anchor": "W",
      "extrapolated": true
    },
    {
      "token": "pink-200",
      "base": "accent",
      "pct": 27,
      "anchor": "W",
      "extrapolated": true
    },
    {
      "token": "pink-100",
      "base": "accent",
      "pct": 13,
      "anchor": "W"
    },
    {
      "token": "pink-50",
      "base": "accent",
      "pct": 6,
      "anchor": "W"
    }
  ]
};
