/**
 * design-system:tokens — builds tokens/tokens.json (DTCG) into the four
 * platform targets with style-dictionary v4 + custom formats, and regenerates
 * the TS mirror of palette-recipe.json consumed by derivePalette().
 *
 * Outputs (committed — generated native copies are synced per ds-01):
 *   build/web/tokens.css        Lumira CSS custom properties (+ dark block)
 *   build/web/tokens.ts         typed constants + web CSS composite strings
 *   build/native/tokens.ts      RN module (unitless, no web composites)
 *   build/kotlin/LumiraTokens.kt   Compose object
 *   build/swift/LumiraTokens.swift Swift enum + SwiftUI Color
 *   src/theme/palette-recipe.data.ts  recipe mirror for the TS executor
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import StyleDictionary from 'style-dictionary';
import { formatCss, formatTsWeb, formatTsNative, formatKotlin, formatSwift } from './lib/formats.mjs';

const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), '..');

StyleDictionary.registerFormat({ name: 'tatame/css', format: formatCss });
StyleDictionary.registerFormat({ name: 'tatame/ts-web', format: formatTsWeb });
StyleDictionary.registerFormat({ name: 'tatame/ts-native', format: formatTsNative });
StyleDictionary.registerFormat({ name: 'tatame/kotlin', format: formatKotlin });
StyleDictionary.registerFormat({ name: 'tatame/swift', format: formatSwift });

const sd = new StyleDictionary({
  source: [join(pkgRoot, 'tokens/tokens.json')],
  platforms: {
    css: {
      buildPath: join(pkgRoot, 'build/web/'),
      files: [{ destination: 'tokens.css', format: 'tatame/css' }],
    },
    tsWeb: {
      buildPath: join(pkgRoot, 'build/web/'),
      files: [{ destination: 'tokens.ts', format: 'tatame/ts-web' }],
    },
    tsNative: {
      buildPath: join(pkgRoot, 'build/native/'),
      files: [{ destination: 'tokens.ts', format: 'tatame/ts-native' }],
    },
    kotlin: {
      buildPath: join(pkgRoot, 'build/kotlin/'),
      files: [{ destination: 'LumiraTokens.kt', format: 'tatame/kotlin' }],
    },
    swift: {
      buildPath: join(pkgRoot, 'build/swift/'),
      files: [{ destination: 'LumiraTokens.swift', format: 'tatame/swift' }],
    },
  },
  log: { verbosity: 'silent' },
});

await sd.buildAllPlatforms();

/* ---- palette-recipe.json -> src/theme/palette-recipe.data.ts mirror ---- */

const recipe = JSON.parse(readFileSync(join(pkgRoot, 'tokens/palette-recipe.json'), 'utf8'));
const { $description: _drop, ...recipeData } = recipe;

const mirror = `/**
 * GENERATED FILE — do not edit by hand.
 *
 * TypeScript mirror of \`tokens/palette-recipe.json\`, regenerated by the
 * \`design-system:tokens\` target (tokens/build.mjs). The JSON file is the
 * canonical recipe; this module exists so TS source never imports JSON
 * (nodenext + import attributes friction). A vitest test asserts this
 * mirror is byte-identical in content to the JSON.
 */

export type RecipeBase = 'deep' | 'vibrant' | 'accent';

export interface RecipeRule {
  readonly base: RecipeBase;
  readonly pct: number;
  /** Literal hex, an input slot name, symbolic "W", or null (plain copy). */
  readonly anchor: string | null;
}

export interface RecipeEntry extends Partial<RecipeRule> {
  readonly token: string;
  readonly modes?: { readonly light: RecipeRule; readonly dark: RecipeRule };
  readonly extrapolated?: boolean;
}

export interface PaletteRecipe {
  readonly anchors: { readonly W: { readonly light: string; readonly dark: string } };
  readonly entries: readonly RecipeEntry[];
}

export const PALETTE_RECIPE: PaletteRecipe = ${JSON.stringify(recipeData, null, 2)};
`;

writeFileSync(join(pkgRoot, 'src/theme/palette-recipe.data.ts'), mirror);

/* ---- report ---- */

const count = (file, re) => (readFileSync(join(pkgRoot, file), 'utf8').match(re) ?? []).length;
mkdirSync(join(pkgRoot, 'build'), { recursive: true });
console.log('[design-system:tokens] built:');
console.log(`  build/web/tokens.css        ${count('build/web/tokens.css', /^ {2}--/gm)} custom properties`);
console.log(`  build/web/tokens.ts         ${count('build/web/tokens.ts', /"[^"\n]+": /g)} entries`);
console.log(`  build/native/tokens.ts      ${count('build/native/tokens.ts', /"[^"\n]+": /g)} entries`);
console.log(`  build/kotlin/LumiraTokens.kt   ${count('build/kotlin/LumiraTokens.kt', /val /g)} vals`);
console.log(`  build/swift/LumiraTokens.swift ${count('build/swift/LumiraTokens.swift', /static let /g)} constants`);
console.log('  src/theme/palette-recipe.data.ts (recipe mirror)');
